package com.zhjie.dao.zsManage;

import java.util.List;
import java.util.Map;

import com.zhjie.pojo.zsManage.KnowledgeInfo;

public interface KnowledgeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int insert(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    KnowledgeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_bank_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgeInfo record);
    /**
     * 查询
     * @param params
     * @return
     */
    List<KnowledgeInfo> select(Map<String,Object> params);
    /**
     * 保存
     * @param params
     * @return
     */
    int saveOrUpdate(Map<String,Object> params);
}