package com.zhjie.dao.code;

import java.util.List;
import java.util.Map;

import com.zhjie.pojo.code.CodeDetail;

public interface CodeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    int insert(CodeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    int insertSelective(CodeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    CodeDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeDetail record);
    
    List<CodeDetail> select(Map<String,Object> params);
}