package com.zhjie.dao.code;

import java.util.List;
import java.util.Map;

import com.zhjie.pojo.code.CodeInfo;

public interface CodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    int insert(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    int insertSelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    CodeInfo selectByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeInfo record);
    
    List<CodeInfo> select(Map<String,Object> params);
}