package com.zhjie.dao.fwb;

import java.util.List;
import java.util.Map;

import com.zhjie.pojo.fwb.FwbInfo;

public interface FwbInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    int insert(FwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    int insertSelective(FwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    FwbInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FwbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_fwb_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FwbInfo record);
    /**
     * 查询数据
     * @param params
     * @return
     */
    List<FwbInfo> select(Map<String,Object> params);
}